###############################################################################
# Development
# Because DigitalOcean App Platform will always run the Dockerfile to the end,
# this file exists.
###############################################################################

# Lightly modified from drupal:9 to not create a project inside the container
FROM php:7.4-apache-buster as base

# Production PHP.ini
RUN cp ${PHP_INI_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini

# install the PHP extensions we need
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions gd opcache pdo_pgsql zip

# Enable apache extensions
RUN a2enmod rewrite

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=60'; \
		echo 'opcache.fast_shutdown=1'; \
	} > ${PHP_INI_DIR}/conf.d/opcache-recommended.ini
RUN { \
		echo 'memory_limit=256M'; \
	} > ${PHP_INI_DIR}/conf.d/drupal.ini

RUN set -eux; \
    # Need some extras for certain composer downloads
    apt-get update; \
    apt-get install -y --no-install-recommends git openssh-client unzip
COPY docker/ssh_known_hosts /etc/ssh/ssh_known_hosts

# Setup entrypoint
COPY docker/entrypoint.sh /usr/local/bin/app_entrypoint
ENTRYPOINT /usr/local/bin/app_entrypoint

# https://github.com/drupal/drupal/blob/9.0.1/composer.lock#L4052-L4053
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/

# https://www.drupal.org/node/3060/release
ENV PATH=${PATH}:/opt/drupal/vendor/bin

COPY app /opt/drupal
WORKDIR /opt/drupal

RUN set -eux; \
	export COMPOSER_HOME="$(mktemp -d)"; \
    composer install --no-interaction --optimize-autoloader --no-dev; \
	# delete composer cache
	rm -rf "$COMPOSER_HOME"
RUN set -eux; \
    mkdir -p web/sites/default/files; \
	chown -Rv www-data:www-data web/sites web/modules web/themes config/sync; \
	rmdir /var/www/html; \
	ln -sf /opt/drupal/web /var/www/html;

#######################################
# APP DEVELOPMENT SUPPORT
#######################################
FROM base as app_dev

# Enable Drupal's development mode
ENV APP_DEV_MODE=1

# Development php.ini
RUN cp ${PHP_INI_DIR}/php.ini-development ${PHP_INI_DIR}/php.ini

# Install xdebug
RUN install-php-extensions xdebug
RUN { \
		echo 'xdebug.mode=debug'; \
		echo 'xdebug.discover_client_host=1'; \
	} >> ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini

# Setup mailhog
RUN { \
		echo 'sendmail_path = /usr/sbin/sendmail -S mail:1025'; \
	} > ${PHP_INI_DIR}/conf.d/mailhog.ini

# Install pandoc (needed for data migrations)
RUN apt-get update; \
	apt-get install -y --no-install-recommends pandoc
